"""initial schema

Revision ID: 000d3091a68f
Revises:
Create Date: 2026-08-05 15:50:07.130318
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "000d3091a68f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("role", sa.Enum("OWNER", "DOCTOR", "ADMIN", name="userrole"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=True),
        sa.Column("event_metadata", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_actor_user_id"), ["actor_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_resource_type"), ["resource_type"], unique=False
        )

    op.create_table(
        "doctor_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("license_number", sa.String(length=100), nullable=False),
        sa.Column("qualification", sa.String(length=255), nullable=False),
        sa.Column("specialization", sa.String(length=160), nullable=True),
        sa.Column("experience_years", sa.Integer(), nullable=False),
        sa.Column("hospital_name", sa.String(length=200), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum("PENDING", "VERIFIED", "REJECTED", name="verificationstatus"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("verification_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("license_number"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("doctor_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_doctor_profiles_verification_status"),
            ["verification_status"],
            unique=False,
        )

    op.create_table(
        "pets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("species", sa.String(length=80), nullable=False),
        sa.Column("breed", sa.String(length=120), nullable=True),
        sa.Column("sex", sa.String(length=40), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("profile_image_url", sa.String(length=500), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pets_is_archived"), ["is_archived"], unique=False)
        batch_op.create_index(batch_op.f("ix_pets_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "doctor_availability",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("doctor_id", sa.String(length=36), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_booked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctor_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("doctor_availability", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_doctor_availability_doctor_id"), ["doctor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_doctor_availability_ends_at"), ["ends_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_doctor_availability_is_booked"), ["is_booked"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_doctor_availability_starts_at"), ["starts_at"], unique=False
        )

    op.create_table(
        "medical_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pet_id", sa.String(length=36), nullable=False),
        sa.Column("recorded_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("record_type", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("document_url", sa.String(length=500), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("medical_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_medical_records_is_archived"), ["is_archived"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_medical_records_pet_id"), ["pet_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_medical_records_record_type"), ["record_type"], unique=False
        )

    op.create_table(
        "appointments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pet_id", sa.String(length=36), nullable=False),
        sa.Column("doctor_id", sa.String(length=36), nullable=False),
        sa.Column("availability_id", sa.String(length=36), nullable=False),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("consultation_type", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "REQUESTED",
                "CONFIRMED",
                "REJECTED",
                "CANCELLED",
                "COMPLETED",
                "NO_SHOW",
                name="appointmentstatus",
            ),
            nullable=False,
        ),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["availability_id"],
            ["doctor_availability.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctor_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_appointments_availability_id"), ["availability_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_appointments_doctor_id"), ["doctor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_appointments_pet_id"), ["pet_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_appointments_scheduled_start"), ["scheduled_start"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_appointments_status"), ["status"], unique=False)

    op.create_table(
        "medical_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("medical_record_id", sa.String(length=36), nullable=False),
        sa.Column("uploaded_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["medical_record_id"],
            ["medical_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    with op.batch_alter_table("medical_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_medical_documents_medical_record_id"),
            ["medical_record_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_medical_documents_uploaded_by_user_id"),
            ["uploaded_by_user_id"],
            unique=False,
        )

    op.create_table(
        "consents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("appointment_id", sa.String(length=36), nullable=True),
        sa.Column("consent_type", sa.String(length=80), nullable=False),
        sa.Column("policy_version", sa.String(length=40), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("consents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_consents_consent_type"), ["consent_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_consents_user_id"), ["user_id"], unique=False)

    op.create_table(
        "consultations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("appointment_id", sa.String(length=36), nullable=False),
        sa.Column("diagnosis", sa.Text(), nullable=True),
        sa.Column("doctor_notes", sa.Text(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("ai_summary_draft", sa.Text(), nullable=True),
        sa.Column("approved_summary", sa.Text(), nullable=True),
        sa.Column("follow_up_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("appointment_id"),
    )
    op.create_table(
        "prescriptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("consultation_id", sa.String(length=36), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("recommended_tests", sa.JSON(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["consultation_id"],
            ["consultations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("consultation_id"),
    )
    op.create_table(
        "reminders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("pet_id", sa.String(length=36), nullable=False),
        sa.Column("source_consultation_id", sa.String(length=36), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "reminder_type",
            sa.Enum(
                "MEDICINE", "VACCINATION", "APPOINTMENT", "FOLLOW_UP", "CUSTOM", name="remindertype"
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("repeat_interval_hours", sa.Integer(), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_consultation_id"],
            ["consultations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reminders_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_reminders_pet_id"), ["pet_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_reminders_reminder_type"), ["reminder_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reminders_scheduled_for"), ["scheduled_for"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reminders_source_consultation_id"),
            ["source_consultation_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_reminders_user_id"), ["user_id"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("reminder_id", sa.String(length=36), nullable=True),
        sa.Column(
            "notification_type",
            sa.Enum("REMINDER", "APPOINTMENT", "PRESCRIPTION", "SYSTEM", name="notificationtype"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reminder_id"],
            ["reminders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_notification_type"), ["notification_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_read_at"), ["read_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notifications_reminder_id"), ["reminder_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)

    op.create_table(
        "prescription_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("prescription_id", sa.String(length=36), nullable=False),
        sa.Column("medicine_name", sa.String(length=200), nullable=False),
        sa.Column("dosage", sa.String(length=120), nullable=False),
        sa.Column("frequency", sa.String(length=120), nullable=False),
        sa.Column("duration", sa.String(length=120), nullable=False),
        sa.Column("route", sa.String(length=80), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prescription_id"],
            ["prescriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("prescription_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_prescription_items_prescription_id"), ["prescription_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prescription_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prescription_items_prescription_id"))

    op.drop_table("prescription_items")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_reminder_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_read_at"))
        batch_op.drop_index(batch_op.f("ix_notifications_notification_type"))

    op.drop_table("notifications")
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reminders_user_id"))
        batch_op.drop_index(batch_op.f("ix_reminders_source_consultation_id"))
        batch_op.drop_index(batch_op.f("ix_reminders_scheduled_for"))
        batch_op.drop_index(batch_op.f("ix_reminders_reminder_type"))
        batch_op.drop_index(batch_op.f("ix_reminders_pet_id"))
        batch_op.drop_index(batch_op.f("ix_reminders_is_active"))

    op.drop_table("reminders")
    op.drop_table("prescriptions")
    op.drop_table("consultations")
    with op.batch_alter_table("consents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consents_user_id"))
        batch_op.drop_index(batch_op.f("ix_consents_consent_type"))

    op.drop_table("consents")
    with op.batch_alter_table("medical_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_medical_documents_uploaded_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_medical_documents_medical_record_id"))

    op.drop_table("medical_documents")
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appointments_status"))
        batch_op.drop_index(batch_op.f("ix_appointments_scheduled_start"))
        batch_op.drop_index(batch_op.f("ix_appointments_pet_id"))
        batch_op.drop_index(batch_op.f("ix_appointments_doctor_id"))
        batch_op.drop_index(batch_op.f("ix_appointments_availability_id"))

    op.drop_table("appointments")
    with op.batch_alter_table("medical_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_medical_records_record_type"))
        batch_op.drop_index(batch_op.f("ix_medical_records_pet_id"))
        batch_op.drop_index(batch_op.f("ix_medical_records_is_archived"))

    op.drop_table("medical_records")
    with op.batch_alter_table("doctor_availability", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_doctor_availability_starts_at"))
        batch_op.drop_index(batch_op.f("ix_doctor_availability_is_booked"))
        batch_op.drop_index(batch_op.f("ix_doctor_availability_ends_at"))
        batch_op.drop_index(batch_op.f("ix_doctor_availability_doctor_id"))

    op.drop_table("doctor_availability")
    with op.batch_alter_table("pets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pets_owner_id"))
        batch_op.drop_index(batch_op.f("ix_pets_is_archived"))

    op.drop_table("pets")
    with op.batch_alter_table("doctor_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_doctor_profiles_verification_status"))

    op.drop_table("doctor_profiles")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_resource_type"))
        batch_op.drop_index(batch_op.f("ix_audit_events_actor_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_action"))

    op.drop_table("audit_events")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###

    # Not part of the autogenerated block above: DROP TABLE never drops the
    # Postgres enum types those columns used, so a downgrade all the way to
    # base left them dangling — re-running upgrade from empty then failed
    # with "type already exists" on the first one autogenerate re-creates.
    # No-op on SQLite, which has no such types.
    for enum_name in (
        "userrole",
        "verificationstatus",
        "appointmentstatus",
        "remindertype",
        "notificationtype",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
